name: Trigger auto deployment for aca-flask-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aca-flask-app-AutoDeployTrigger-dcca9e45-a1a3-4686-bb9e-89df3bbd3208.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acrdemo0831.azurecr.io
          username: ${{ secrets.ACAFLASKAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.ACAFLASKAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrdemo0831.azurecr.io/flask-hello-world:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACAFLASKAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n aca-flask-app -g aca-demo-0831 --server acrdemo0831.azurecr.io --username  ${{ secrets.ACAFLASKAPP_REGISTRY_USERNAME }} --password ${{ secrets.ACAFLASKAPP_REGISTRY_PASSWORD }}
            az containerapp update -n aca-flask-app -g aca-demo-0831 --image acrdemo0831.azurecr.io/flask-hello-world:${{ github.sha }}
